import "dotenv/config";

import { getSqlPool } from "./server/sqlserver.js";

async function run() {
  const pool = await getSqlPool();

  await pool.request().query(`
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='KS0003' AND TABLE_NAME='KS00011')
    CREATE TABLE KS0003.KS00011 (
      GUIDBOLETO      UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
      GUIDLANCAMENTO  UNIQUEIDENTIFIER NOT NULL,
      GUIDENTIDADE    UNIQUEIDENTIFIER NOT NULL,
      BANCO           NVARCHAR(20)     NOT NULL,
      VALOR           DECIMAL(15,2)    NOT NULL,
      VENCIMENTO      DATE             NOT NULL,
      STATUS          NVARCHAR(20)     NOT NULL DEFAULT 'PENDENTE',
      NOSSONUMERO     NVARCHAR(80)     NULL,
      LINHADIGITAVEL  NVARCHAR(160)    NULL,
      CODIGOBARRAS    NVARCHAR(120)    NULL,
      URLPDF          NVARCHAR(1000)   NULL,
      EXTERNALID      NVARCHAR(160)    NULL,
      MENSAGEMERRO    NVARCHAR(1000)   NULL,
      DATACADASTRO    DATETIME         NOT NULL DEFAULT GETDATE(),
      ULTIMAALTERACAO DATETIME         NOT NULL DEFAULT GETDATE()
    )
  `);

  await pool.request().query(`
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_KS00011_LANCAMENTO' AND object_id=OBJECT_ID('KS0003.KS00011'))
      CREATE INDEX IX_KS00011_LANCAMENTO ON KS0003.KS00011 (GUIDENTIDADE, GUIDLANCAMENTO, ULTIMAALTERACAO)
  `);

  await pool.request().query(`
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='KS0003' AND TABLE_NAME='KS00012')
    CREATE TABLE KS0003.KS00012 (
      GUIDEVENTO      UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
      GUIDBOLETO      UNIQUEIDENTIFIER NOT NULL,
      GUIDENTIDADE    UNIQUEIDENTIFIER NOT NULL,
      TIPOEVENTO      NVARCHAR(40)     NOT NULL,
      DESCRICAO       NVARCHAR(500)    NULL,
      REQUESTJSON     NVARCHAR(MAX)    NULL,
      RESPONSEJSON    NVARCHAR(MAX)    NULL,
      DATACADASTRO    DATETIME         NOT NULL DEFAULT GETDATE(),
      ULTIMAALTERACAO DATETIME         NOT NULL DEFAULT GETDATE()
    )
  `);

  await pool.request().query(`
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_KS00012_BOLETO' AND object_id=OBJECT_ID('KS0003.KS00012'))
      CREATE INDEX IX_KS00012_BOLETO ON KS0003.KS00012 (GUIDENTIDADE, GUIDBOLETO, DATACADASTRO)
  `);

  console.log("Tabelas de boletos em Contas a Receber verificadas/criadas.");
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
