import "dotenv/config";
import { getSqlPool } from "./server/sqlserver.js";

async function run() {
  const pool = await getSqlPool();

  await pool.request().query(`
    IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'KS0005')
      EXEC('CREATE SCHEMA KS0005')
  `);
  console.log("Schema KS0005 OK");

  await pool.request().query(`
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='KS0005' AND TABLE_NAME='KS00001')
    CREATE TABLE KS0005.KS00001 (
      GUIDMOVIMENTO   UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
      GUIDFUNCIONARIO UNIQUEIDENTIFIER NOT NULL,
      TIPO            NVARCHAR(20)     NOT NULL CHECK (TIPO IN ('SALARIO','COMISSAO','VALE')),
      DESCRICAO       NVARCHAR(200)    NOT NULL,
      VALOR           DECIMAL(15,2)    NOT NULL DEFAULT 0,
      DATAMOVIMENTO   DATE             NOT NULL,
      COMPETENCIA     NVARCHAR(7)      NOT NULL,
      STATUS          NVARCHAR(20)     NOT NULL DEFAULT 'ABERTO' CHECK (STATUS IN ('ABERTO','FECHADO','CANCELADO')),
      GUIDFECHAMENTO  UNIQUEIDENTIFIER NULL,
      GUIDLANCCAIXA   UNIQUEIDENTIFIER NULL,
      GUIDCONTACAIXA  UNIQUEIDENTIFIER NULL,
      GUIDNATUREZA    UNIQUEIDENTIFIER NULL,
      GUIDCENTRO      UNIQUEIDENTIFIER NULL,
      OBSERVACAO      NVARCHAR(500)    NULL,
      GUIDENTIDADE    UNIQUEIDENTIFIER NOT NULL,
      DATACADASTRO    DATETIME         NOT NULL DEFAULT GETDATE(),
      ULTIMAALTERACAO DATETIME         NOT NULL DEFAULT GETDATE()
    )
  `);
  console.log("KS0005.KS00001 movimentos OK");

  await pool.request().query(`
    IF COL_LENGTH('KS0005.KS00001', 'GUIDLANCCAIXA') IS NULL
      ALTER TABLE KS0005.KS00001 ADD GUIDLANCCAIXA UNIQUEIDENTIFIER NULL
    IF COL_LENGTH('KS0005.KS00001', 'GUIDCONTACAIXA') IS NULL
      ALTER TABLE KS0005.KS00001 ADD GUIDCONTACAIXA UNIQUEIDENTIFIER NULL
    IF COL_LENGTH('KS0005.KS00001', 'GUIDNATUREZA') IS NULL
      ALTER TABLE KS0005.KS00001 ADD GUIDNATUREZA UNIQUEIDENTIFIER NULL
    IF COL_LENGTH('KS0005.KS00001', 'GUIDCENTRO') IS NULL
      ALTER TABLE KS0005.KS00001 ADD GUIDCENTRO UNIQUEIDENTIFIER NULL
  `);
  console.log("Vinculos de vale com caixa OK");

  await pool.request().query(`
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='KS0005' AND TABLE_NAME='KS00002')
    CREATE TABLE KS0005.KS00002 (
      GUIDFECHAMENTO  UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
      COMPETENCIA     NVARCHAR(7)      NOT NULL,
      DTINICIO        DATE             NOT NULL,
      DTFIM           DATE             NOT NULL,
      DTVENCIMENTO    DATE             NOT NULL,
      TOTALSALARIO    DECIMAL(15,2)    NOT NULL DEFAULT 0,
      TOTALCOMISSAO   DECIMAL(15,2)    NOT NULL DEFAULT 0,
      TOTALVALE       DECIMAL(15,2)    NOT NULL DEFAULT 0,
      TOTALLIQUIDO    DECIMAL(15,2)    NOT NULL DEFAULT 0,
      STATUS          NVARCHAR(20)     NOT NULL DEFAULT 'ABERTO' CHECK (STATUS IN ('ABERTO','PAGO','CANCELADO')),
      OBSERVACAO      NVARCHAR(500)    NULL,
      GUIDENTIDADE    UNIQUEIDENTIFIER NOT NULL,
      DATACADASTRO    DATETIME         NOT NULL DEFAULT GETDATE(),
      ULTIMAALTERACAO DATETIME         NOT NULL DEFAULT GETDATE()
    )
  `);
  console.log("KS0005.KS00002 fechamentos OK");

  await pool.request().query(`
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='KS0005' AND TABLE_NAME='KS00003')
    CREATE TABLE KS0005.KS00003 (
      GUIDITEM        UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
      GUIDFECHAMENTO  UNIQUEIDENTIFIER NOT NULL,
      GUIDFUNCIONARIO UNIQUEIDENTIFIER NOT NULL,
      TOTALSALARIO    DECIMAL(15,2)    NOT NULL DEFAULT 0,
      TOTALCOMISSAO   DECIMAL(15,2)    NOT NULL DEFAULT 0,
      TOTALVALE       DECIMAL(15,2)    NOT NULL DEFAULT 0,
      VALORLIQUIDO    DECIMAL(15,2)    NOT NULL DEFAULT 0,
      GUIDLANCPAGAR   UNIQUEIDENTIFIER NULL,
      DATACADASTRO    DATETIME         NOT NULL DEFAULT GETDATE(),
      ULTIMAALTERACAO DATETIME         NOT NULL DEFAULT GETDATE()
    )
  `);
  console.log("KS0005.KS00003 itens de fechamento OK");

  await pool.request().query(`
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_KS0005_00001_ENT_COMP_STATUS')
      CREATE INDEX IX_KS0005_00001_ENT_COMP_STATUS ON KS0005.KS00001 (GUIDENTIDADE, COMPETENCIA, STATUS)
  `);
  await pool.request().query(`
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_KS0005_00002_ENT_COMP')
      CREATE INDEX IX_KS0005_00002_ENT_COMP ON KS0005.KS00002 (GUIDENTIDADE, COMPETENCIA)
  `);

  console.log("Modulo de funcionarios e pagamentos criado com sucesso.");
}

run().catch((err) => {
  console.error("Erro ao criar modulo de funcionarios e pagamentos:", err);
  process.exit(1);
});
