IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='KS0004' AND TABLE_NAME='ProdutoUnidadePreco')
BEGIN
  CREATE TABLE KS0004.ProdutoUnidadePreco (
    ID                INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    GUIDPRECO         UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    GUIDPRODUTO       UNIQUEIDENTIFIER NOT NULL,
    CODPRODUTO        INT NULL,
    UNIDADE           NVARCHAR(6) NOT NULL,
    FATORCONVERSAO    DECIMAL(15,4) NOT NULL CONSTRAINT DF_ProdutoUnidadePreco_Fator DEFAULT 1,
    QUANTIDADEMINIMA  DECIMAL(15,4) NOT NULL,
    DESCRICAOPRECO    NVARCHAR(60) NULL,
    PRECOVENDA        DECIMAL(15,4) NOT NULL,
    ATIVO             BIT NOT NULL CONSTRAINT DF_ProdutoUnidadePreco_Ativo DEFAULT 1,
    GUIDENTIDADE      UNIQUEIDENTIFIER NOT NULL,
    DATACADASTRO      DATETIME NOT NULL CONSTRAINT DF_ProdutoUnidadePreco_DataCadastro DEFAULT GETDATE(),
    ULTIMAALTERACAO   DATETIME NOT NULL CONSTRAINT DF_ProdutoUnidadePreco_UltimaAlteracao DEFAULT GETDATE()
  );
END;

IF COL_LENGTH('KS0004.ProdutoUnidadePreco','GUIDPRECO') IS NULL
  ALTER TABLE KS0004.ProdutoUnidadePreco ADD GUIDPRECO UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_ProdutoUnidadePreco_Guid DEFAULT NEWID();

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='UX_ProdutoUnidadePreco_Produto_Unidade_Qtd' AND object_id=OBJECT_ID('KS0004.ProdutoUnidadePreco'))
  CREATE UNIQUE INDEX UX_ProdutoUnidadePreco_Produto_Unidade_Qtd
  ON KS0004.ProdutoUnidadePreco (GUIDENTIDADE, GUIDPRODUTO, UNIDADE, QUANTIDADEMINIMA);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_ProdutoUnidadePreco_Calculo' AND object_id=OBJECT_ID('KS0004.ProdutoUnidadePreco'))
  CREATE INDEX IX_ProdutoUnidadePreco_Calculo
  ON KS0004.ProdutoUnidadePreco (GUIDENTIDADE, GUIDPRODUTO, UNIDADE, ATIVO, QUANTIDADEMINIMA DESC);

IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name='CK_ProdutoUnidadePreco_Valores' AND parent_object_id=OBJECT_ID('KS0004.ProdutoUnidadePreco'))
  ALTER TABLE KS0004.ProdutoUnidadePreco WITH CHECK ADD CONSTRAINT CK_ProdutoUnidadePreco_Valores
  CHECK (FATORCONVERSAO > 0 AND QUANTIDADEMINIMA > 0 AND PRECOVENDA > 0);
